#!/usr/bin/env bash
# install nginx on web server and do configurations

apt update
apt install -y nginx
ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
