#!/usr/bin/env bash
# install nginx on web server and do configurations

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee usr/share/nginx/html/index.html
sudo service nginx start
