#!/usr/bin/env bash
# install nginx on web server and do configurations

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
