#!/usr/bin/env bash
# Configure the server to enable Nginx on 80 port
# of all the server’s active IPv4 IPs

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
