#!/usr/bin/env bash
# displays numbers from 1 to 100
# displays FizzBuzz when number is multiple by 3 and 5
# displays Fizz when number is multiple by 3
# displays Buzz when number is multiple by 5
# otherwise displays the numbers in a list format

for ((i = 1; i <= 100; i++));
do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
