#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

hr=0
min=1
while ((hour < 13))
do
	echo "Hour: $hr"
	((h++))
	
	min=1
	while ((min < 60))
	do
		echo "$min"
		((min++))
	done
done
