#!/usr/bin/env bash
# displays content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

for file in *;
do
	if [ -f "$file" ]; then
		f="${file#*-}"
	echo "$f"
	fi
done
