#!/usr/bin/env bash
# Run nginx as the nginx user

# Update Nginx configuration
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# change ownership and permissions of config file
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

# Update Nginx default site configuration
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

pkill apache2
sudo -u nginx service nginx restart
