#!/usr/bin/env bash
# Run nginx as the nginx user
pkill apache2
sed -i 's/user www-data;/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
